name: Auto Semver
description: Easily manage versioning for your repository
branding:
  icon: box
  color: orange
runs:
  using: node16
  main: dist/main.js
inputs:
  token:
    required: true
    description: |
      a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)
      or `${{ github.token }}`. This is used together with the `git` commandline to
      list commits and tags in your repository.
  repository:
    required: true
    description: |
      Which repository to autosemver for. This should normally be set
      to `${{ github.repository }}`.
  type:
    required: true
    description: |
      What type of increment to do on the previous version. Supported values
      are `major`, `minor` and `patch`.
outputs:
  version:
    description: |
      Which repository to autosemver for. This should normally be set
      to `${{ github.repository }}`.
  previous_version:
    description: |
      The highest and currently available semver tag in the repository.
  previous_version_ref:
    description: |
      The commit reference that the highest and currently available
      semver tag is referencing to.
